{% set name = "trackpy" %}
{% set version = "0.7" %}
{% set sha256 = "7c67af8d5242323f4469a3e0157146b42f82be9ae640c4bbff0a8a5888928818" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - numpy >=1.18
    - scipy >=1.4
    - pandas >=1
    - pyyaml
    - matplotlib-base
    - looseversion >=1.0.1
  run:
    - python >={{ python_min }}
    - setuptools
    - numpy >=1.18
    - scipy >=1.4
    - pandas >=1
    - pyyaml
    - matplotlib-base
    - looseversion >=1.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - trackpy

about:
  home: https://github.com/soft-matter/trackpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python particle tracking toolkit
  description: |
    trackpy is a Python package for particle tracking in 2D, 3D,
    and higher dimensions.
  doc_url: http://soft-matter.github.io/trackpy

extra:
  recipe-maintainers:
    - danielballan
    - tacaswell
    - nkeim
    - caspervdw
    - rbnvrw
