{% set name = "trackpy" %}
{% set version = "0.6.0" %}
{% set sha256 = "7b661ebbd6c8299a04f37cdc56926de703dcfba653a21ebbbe01aa7f20181cdf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - numpy >=1.14
    - scipy >=1.1
    - pandas >=0.22
    - pyyaml
    - matplotlib-base
  run:
    - python >=3.6
    - setuptools
    - numpy >=1.14
    - scipy >=1.1
    - pandas >=0.22
    - pyyaml
    - matplotlib-base

test:
  imports:
    - trackpy

about:
  home: https://github.com/soft-matter/trackpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python particle tracking toolkit
  description: |
    trackpy is a Python package for particle tracking in 2D, 3D,
    and higher dimensions.
  doc_url: http://soft-matter.github.io/trackpy

extra:
  recipe-maintainers:
    - danielballan
    - tacaswell
    - nkeim
    - caspervdw
    - rbnvrw
