{% set name = "trackpy" %}
{% set version = "0.4.2" %}
{% set sha256 = "ed3e53087cd98480e09473d774f13077906dca3cbdbc7c7cbb8c2ac6e3d95d70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy >=1.8
    - scipy >=0.12
    - six >=1.8
    - pandas >=0.13
    - pyyaml
    - matplotlib-base
  run:
    - python
    - setuptools
    - numpy >=1.8
    - scipy >=0.12
    - six >=1.8
    - pandas >=0.13
    - pyyaml
    - matplotlib-base

test:
  imports:
    - trackpy

about:
  home: https://github.com/soft-matter/trackpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Python particle tracking toolkit'
  description: |
    trackpy is a Python package for particle tracking in 2D, 3D,
    and higher dimensions.
  doc_url: http://soft-matter.github.io/trackpy

extra:
  recipe-maintainers:
    - danielballan
    - tacaswell
    - nkeim
    - caspervdw
