{% set name = "trackpy" %}
{% set version = "0.6.2rc1" %}
{% set sha256 = "bdc44e9b1207cee938d701f512382c90153c3595173eb15cb0b9fce76d63f2a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - numpy >=1.18
    - scipy >=1.4
    - pandas >=1
    - pyyaml
    - matplotlib-base
    - looseversion >=1.0.1
  run:
    - python >=3.8
    - setuptools
    - numpy >=1.18
    - scipy >=1.4
    - pandas >=1
    - pyyaml
    - matplotlib-base
    - looseversion >=1.0.1

test:
  imports:
    - trackpy

about:
  home: https://github.com/soft-matter/trackpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python particle tracking toolkit
  description: |
    trackpy is a Python package for particle tracking in 2D, 3D,
    and higher dimensions.
  doc_url: http://soft-matter.github.io/trackpy

extra:
  recipe-maintainers:
    - danielballan
    - tacaswell
    - nkeim
    - caspervdw
    - rbnvrw
