travis:
  secure:
    BINSTAR_TOKEN: um9efYIVCDyYgzFb1T+VlTKe1Hun8Q8oDBgmxvdv2hVgWzcx+O9bl8KPSdREb4Bzgs7kMobrx7JYhedrkq1O/25hd41DptobcJ6N169R9PrNYnTGhUmk3bIV/Y8NCo9W+Y8efngodXjdKf/0L8r5gbFIHtsefn0VOjRKdu3w87XyfPiGTWo9OmoztclYFWPjeRTlUJlA7zRBDt7sM0Lhij0Fzwz4zjY8TZKeDe+kspcVp/fpzQuGyZgYJyPxM91jWQBWCNtDsNEpfUEUdZV/Esn6ZwVy8g2NvaNb7IsBlsXnlMue8im0mYrfgmteRszy2ST0VMQXd9AIexDps6naObmc3ebS6a6OiZncJS/CkVApmgFWuG0WPrLjOH0WsH5W+tqGNWlkPUamFEKCqleqYRPInCOXQ1cun4k4mPhq7281MSb7NowMtkPSrklOetBbhNDNOD55QIHhzXshcoekCI3K10HHODy9F2icsADT3/ug7Oa1FH8TKDSX+cbTdpK56lp/rAE9NRCUnXFftU1/ANyvMkCTxvXbAM/T6snSlGR35LBBUMpX8ypNzLonLIciqqwplblOMKsPeoPnXptvwwDvoXnYdFeE/xmnef1jpVBuuYNa7lFff5sqTLFTB3/AcayowINItcntYtAHh6PnldC/h3asJc2kkhanu+qjbGw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
